<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MNX.Application.UseCases.DI" Version="1.0.2" />
    <PackageReference Include="Quartz" Version="3.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MNX.SubscriptionManagement.Domain\MNX.SubscriptionManagement.Domain.Core.csproj" />
  </ItemGroup>

</Project>
